#!/usr/bin/env bash
text_in="$(xsel -o)"
if [ "$text_in" != "" ] 
then
	lang_out=$(echo 'ru') 
	delimiter=$(echo ';') 
	text_wp="$(wget -U "Mozilla/5.0" \
	-qO - "http://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=$lang_out&dt=t&q=$(echo $text_in| \
	sed "s/[\"'<>]//g")"| \
	sed "s/,,,0]],,.*//g" | \
	awk -F'"' '{print $2, $6}' \
	)"
	# echo $text_wp
	text_out=$(python /home/mikhaylov_yv/Programming/My_translator/python_script.py \
				$text_in $delimiter $lang_out $delimiter $text_wp)
	notify-send "$(echo $text_out| awk 'BEGIN{FS=";"}{print $1}')" "$(echo $text_out| awk 'BEGIN{FS=";"}{print $2}')"

fi

